# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Timingz"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/test/Timingz.Tests"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/test/Timingz.PerformanceTests"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/samples/WebApiSample"
    schedule:
      interval: "daily"