name: CI Build

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/alexmg/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build -c Release --no-restore /p:GITHUB_ACTIONS=false

    - name: Run unit tests
      run: dotnet test ./test/Timingz.Tests --no-restore -c Release -v normal --settings ./coverlet.runsettings --results-directory ./coverage

    - name: Move test coverage results
      run: mv ./coverage/**/*.info ./coverage

    - name: Clean
      run: dotnet clean -c Release

    - name: Pack
      run: dotnet pack ./src/Timingz -c Release --output ./nuget /p:NoPackageAnalysis=true

    - name: Publish to GitHub Packages
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push ./nuget/*.nupkg --api-key $NUGET_AUTH_TOKEN --skip-duplicate

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/coverage.info

    - name: Publish to NuGet.org
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push ./nuget/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate