name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  qodana:
    name: Qodana Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          upload-result: ${{ github.ref_name == 'main' || github.ref_name == 'develop' }}
          args: --baseline,qodana.sarif.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}