name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [ develop, master ]

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # https://github.com/cycjimmy/semantic-release-action/issues/79
      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get semantic release version
        uses: cycjimmy/semantic-release-action@v2.6.0
        id: semantic_dry
        with:
          semantic_version: 18.0.1
          dry_run: true
          extra_plugins: |
            @semantic-release/exec@6.0.2
            conventional-changelog-conventionalcommits@4.6.1
    outputs:
      new_release_published: ${{ steps.semantic_dry.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_dry.outputs.new_release_version }}

  test:
    needs: version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Run unit tests
      run: ./build.sh --target test --no-logo

  release:
    needs: [version, test]
    if: needs.version.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # https://github.com/cycjimmy/semantic-release-action/issues/79
      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v2.6.0
        id: semantic
        with:
          semantic_version: 18.0.1
          extra_plugins: |
            @semantic-release/exec@6.0.2
            conventional-changelog-conventionalcommits@4.6.1