name: Pull Request

on:
  push:
    branches:
      - '!main'
      - '!develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Run unit tests
        run: ./build.sh --target test --no-logo